version: "3.8"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: docker
      ConnectionStrings__Default: "server=fcg-db-server.mysql.database.azure.com;port=3306;database=flexibleserverdb;user=fcgadmin@fcg-db-server;password=NovaSenha@123;SslMode=Required"
    depends_on:
      - db

  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_DATABASE: fcgdb
    ports:
      - "3306:3306"
