version: "3.8"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: docker
      ConnectionStrings__Default: "server=db;port=3306;database=fcgdb;user=root;password=${MYSQL_ROOT_PASSWORD}"
    depends_on:
      - db

  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: fcgdb
    ports:
      - "3306:3306"
