name: CD - Deploy to Azure Container App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name fiap-cloud-games-api \
            --resource-group fcg-rg \
            --image fcgregistry.azurecr.io/fiap-cloud-games-api:latest
